services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    # ports:
      # - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert.pem:/etc/nginx/cert.pem:ro
      - ./key.pem:/etc/nginx/key.pem:ro
    network_mode: host
    depends_on:
      - python_server
    restart: always

  python_server:
    build:
      context: .
      dockerfile: python_server.dockerfile
    container_name: python_server
    # ports:
      # - "8000:8000"
      # - "8765:8765"
    working_dir: /app
    network_mode: host
    restart: always